### ISSUE TITLE
Parse failure when comment appears before "syntax" statement

### ISSUE THREAD

**Issue by DexterMagnific** [recap-build/proto-schema-parser#21]
Dear developer,
Thank you a lot for this fantastic library, this is a great piece of work.

I have one small issue: when a comment appear before the "syntax = " statement, the parsing complains but still parses the remaining of the file.

The spec here https://protobuf.dev/programming-guides/proto3/#simple says that:

>  The first line of the file specifies that you’re using proto3 syntax (...). This must be the first non-empty, non-comment line of the file.

So this allows comments to appear before the syntax= line.

**Comment by criccomini** [comment]
Yes, you're correct. This is missing from the ProtobufParser.g4 file and accompanying parser.py. Please submit a PR with the fix. :)

**Comment by criccomini** [comment]
Closed by #23
