### ISSUE TITLE
Any chance to get the option values parsed ?

### ISSUE THREAD

**Issue by DexterMagnific** [recap-build/proto-schema-parser#22]
Dear developer,

As of current code, option values are returned as plain strings.
Do you plan to add parsing to these ?

The format looks like JSON:
https://protobuf.dev/reference/protobuf/textformat-spec/#example

It is called Protobuf Text. It is used to write "message instances" of the proto formats.

Currently what I'm doing is using a slightly modified JSON grammar to perform the parsing.
Thank you

**Comment by criccomini** [comment]
The proto-schema-parser library parses proto2 and proto3 IDL files. It is not meant to parse Protobuf's text format, which is a textual way to serialize data.

> The protocol buffer Text Format Language specifies a syntax for representation of protobuf data in text form
